---
# simple_apache2_configuration/tasks/main.yml

- name: 'Create vhost file for non-SSL'
  ansible.builtin.template:
    src: 'vhost.conf.j2'
    dest: "{{ simple_apache2_configuration_path_to_apache2_vhosts_d }}/{{ simple_apache2_configuration_vhost_filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the apache2 service'

- name: 'Create file for TLS-enabled vhost'
  ansible.builtin.template:
    src: 'vhost-ssl.conf.j2'
    dest: "{{ simple_apache2_configuration_path_to_apache2_vhosts_d }}/{{ simple_apache2_configuration_vhost_ssl_filename }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify:
    - 'Restart the apache2 service'
  when:
    - 'simple_apache2_configuration_enable_tls | bool'

#
# SSL module on non-Suse
#
- name: 'Enable the SSL apache module'
  community.general.apache2_module:
    state: 'present'
    name: 'ssl'
  notify:
    - 'Restart the apache2 service'
  when:
    - 'simple_apache2_configuration_enable_tls | bool'
    - 'ansible_os_family != "Suse"'

#
# SSL module on Suse
#
- name: 'Check if the SSL module is enabled in the openSUSE sysconfig file'
  ansible.builtin.shell:
    cmd: 'grep ^APACHE_MODULES /etc/sysconfig/apache2 |grep -q ssl'
  register: sysconfig_apache2_grep_ssl_module
  changed_when: false
  failed_when: false
  check_mode: false

- name: 'Enable the SSL module in the openSUSE sysconfig file'
  ansible.builtin.lineinfile:
    path: '/etc/sysconfig/apache2'
    regexp: '^APACHE_MODULES="(.*)"'
    line: 'APACHE_MODULES="ssl \1"'
    backrefs: true
  notify:
    - 'Restart the apache2 service'
  when:
    - 'simple_apache2_configuration_enable_tls | bool'
    - 'ansible_os_family == "Suse"'
    - 'sysconfig_apache2_grep_ssl_module.rc != 0'
